// Code generated by Arduino IoT Cloud, DO NOT EDIT.
 
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
 
 
const char THING_ID[]           = "86fc6944-21a5-4447-a980-125dc1b15276";
const char DEVICE_LOGIN_NAME[]  = "7a1770df-b86b-46df-b8de-5a3603eb8d68";
 
const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
 
void onLight1Change();
void onLight2Change();
void onLight3Change();
void onLight4Change();
 
bool light1;
bool light2;
bool light3;
bool light4;
 
void initProperties(){
 
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(light1, READWRITE, ON_CHANGE, onLight1Change);
  ArduinoCloud.addProperty(light2, READWRITE, ON_CHANGE, onLight2Change);
  ArduinoCloud.addProperty(light3, READWRITE, ON_CHANGE, onLight3Change);
  ArduinoCloud.addProperty(light4, READWRITE, ON_CHANGE, onLight4Change);
 
}
 
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);