/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/76d924c2-a70a-4c1a-a984-53bf3a564535 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool bulb1;
  bool bulb2;
  bool bulb3;
  bool bulb4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode (19, OUTPUT);
  pinMode (21, OUTPUT);
  pinMode (22, OUTPUT);
  pinMode (23, OUTPUT);
   
  digitalWrite (19, HIGH);
  digitalWrite (21, HIGH);
  digitalWrite (22, HIGH);
  digitalWrite (23, HIGH);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since Bulb1 is READ_WRITE variable, onBulb1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onBulb1Change()  {
  if (bulb1==1)
  {
    digitalWrite (22, LOW);
  }
  else
  {
    digitalWrite (22, HIGH);
  }
}
/*
  Since Bulb2 is READ_WRITE variable, onBulb2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onBulb2Change()  {
if (bulb2==1)
  {
    digitalWrite (22, LOW);
  }
  else
  {
    digitalWrite (22, HIGH);
  }
}
/*
  Since Bulb3 is READ_WRITE variable, onBulb3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onBulb3Change()  {
  if (bulb3==1)
  {
    digitalWrite (22, LOW);
  }
  else
  {
    digitalWrite (22, HIGH);
  }
}
/*
  Since Bulb4 is READ_WRITE variable, onBulb4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onBulb4Change()  {
 if (bulb4==1)
  {
    digitalWrite (22, LOW);
  }
  else
  {
    digitalWrite (22, HIGH);
  }
}
